name: HIREME
description: 
meta_description: 

markdown: kramdown
highligher: rouge
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://aquaranto.github.io/'
author:         'Amanda Quaranto-Schulte'

