name: HIREMEv2.0
description: 
meta_description: 

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://aquaranto.github.io/'
author:         'Amanda Quaranto'

